/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import {fadeOnBeforeCompile} from './utils/faedMaterial'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Cloud(props) {
  const { nodes, materials } = useGLTF('/Cloud.glb')
  return (
    <group {...props} dispose={null} scale={0.5} >
      <mesh

        geometry={nodes.Sphere007.geometry}
        position={[2.903, 0.974, -0.244]}>
        <meshStandardMaterial metalness={1.0} roughness={1} transparent  opacity={0.90} envMapIntensity={2}   onBeforeCompile={fadeOnBeforeCompile}
/>
      </mesh>
    </group>
  )
}

useGLTF.preload('/Cloud.glb')
